### ISSUE TITLE
Robot Framework 3.0 compatibility issue with testrobot.keyword

### ISSUE THREAD

**Issue by joongh** [zimmermanncode/robotframework-tools#1]
I got same malfunction as "[RemoteRobot pass built-in exceptions](https://bitbucket.org/userzimmermann/robotframework-tools/issues/4/remoterobot-pass-built-in-exceptions)" with robotframework-tools 0.1a141 and robotframework 3.0

I think this occurs because NormalRunner is renamed to StepRunner in robotframework 3.0
Here is related issue.
https://github.com/robotframework/robotframework/commit/2841582c4aa92f9388f4e841c1ac139ea3589abc

**Comment by espositocode** [comment]
I'm having the same problem (I mistakenly created a duplicate issue: #2). In the meantime, I found it was easier to fork the original RobotRemoteServer to support multiple libraries.

**Comment by userzimmermann** [comment]
Hi @joongh :) Thanks for your hint about `StepRunner`. It saved me a lot of time. But I had to dig a bit deeper. The actual exception catching now happens in `StatusReporter`. Instead of just monkey patching `NormalRunner` I must patch `StatusReporter._get_failure()` now:
https://github.com/zimmermanncode/robotframework-tools/commit/680223875cfdaa8ea8ccef8df82c77f285c627f3

**Comment by userzimmermann** [comment]
Hi @jontayesp :) After solving the basic issue I realized there are some further problems with `RemoteRobot` and Robot 3.0. I will fix them next and make a new release afterwards.
Maybe you will give my robottools another try then ;)

**Comment by espositocode** [comment]
@userzimmermann i will, thanks!

**Comment by userzimmermann** [comment]
Extended the basic fix a bit more: https://github.com/zimmermanncode/robotframework-tools/commit/44c19a957cd321dbea0d974eec54098f55602a11
And solved the additional `RemoteRobot` problem: https://github.com/zimmermanncode/robotframework-tools/commit/2879f8abbdd42327ee7ac43fd42c9f8d1881c525

Some tests for that stuff and the new release will be ready...

**Comment by userzimmermann** [comment]
So... finally :) Everything in [0.1rc1](https://github.com/zimmermanncode/robotframework-tools/releases/tag/0.1rc1) runs properly with RFW **2.8.7 - 3.0**
Thanks @joongh @jontayesp for your patience, if there is any left ;)
